### ISSUE TITLE
Docker compose continually restarts

### ISSUE THREAD

**Issue by jgeorge1983** [bropat/eufy-security-ws#104]
### Ask your question

Hi,

I am trying to run this via docker on a pi4, below is my compose file:
```
version: "2"
services:
  eufy:
    container_name: eufy
    image: bropat/eufy-security-ws:latest
    ports:
      - '3006:3006'
    environment:
      - username=<my username>
      - PASSWORD=<my password>
    volumes:
      - /home/pi/docker/eufy/data:/data
    restart: unless-stopped
    privileged: true
```
but when i start it, it continually shows:

R ID   IMAGE                                             COMMAND                  CREATED          STATUS                        PORTS                                                                                  NAMES
f6fb4ddcd2cc   bropat/eufy-security-ws:latest                    "docker-entrypoint.s…"   14 seconds ago   Restarting (1) 1 second ago                                                                                          eufy

Sorry for the bad formatting there.

Am i missing something obvious? I changed the port as i have zwave running on 3000
I am on node v10.24.0 - is that really old?

Thanks,
Jay
