### ISSUE TITLE
Unable to start driver Request

### ISSUE THREAD

**Issue by Waldorf3** [bropat/eufy-security-ws#111]
### Ask your question

I'm not sure if I'm configuring this right.  I have the following docker-compose.yml:

```
version: '2'
services:
  eufy:
    container_name: eufy
    image: bropat/eufy-security-ws
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /media/private/eufy:/data
    environment:
      - USERNAME=(my email)
      - PASSWORD=(my password)
      - COUNTRY=US
      - LANGUAGE=en
      - ACCEPT_INVITATIONS=true
```
If I understand correct, from this it should be able to connect to Eufy servers and obtain camera details, but I get the error below?   

```
eufy  | Unable to start driver RequestError: getaddrinfo EAI_AGAIN extend.eufylife.com
eufy  |     at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:962:111)
eufy  |     at Object.onceWrapper (node:events:642:26)
eufy  |     at ClientRequest.emit (node:events:539:35)
eufy  |     at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
eufy  |     at TLSSocket.socketErrorListener (node:_http_client:454:9)
eufy  |     at TLSSocket.emit (node:events:527:28)
eufy  |     at emitErrorNT (node:internal/streams/destroy:157:8)
eufy  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)

eufy  |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
eufy  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
eufy  |   code: 'EAI_AGAIN',
eufy  |   timings: {
eufy  |     start: 1653345856676,
eufy  |     socket: 1653345856676,
eufy  |     lookup: 1653345861682,
eufy  |     connect: undefined,
eufy  |     secureConnect: undefined,
eufy  |     upload: undefined,
eufy  |     response: undefined,
eufy  |     end: undefined,
eufy  |     error: 1653345861683,
eufy  |     abort: undefined,
eufy  |     phases: {
eufy  |       wait: 0,
eufy  |       dns: 5006,
eufy  |       tcp: undefined,
eufy  |       tls: undefined,
eufy  |       request: undefined,
eufy  |       firstByte: undefined,
eufy  |       download: undefined,
eufy  |       total: 5007
eufy  |     }
eufy  |   }
eufy  | }
```

**Comment by Waldorf3** [comment]
Actually I just checked docker logs again, and now it seems to have connected:
```
eufy  | 2022-05-24 09:39:56.625  INFO  Eufy Security server listening on host 0.0.0.0, port 3000
eufy  | 2022-05-24 09:39:58.894  INFO  Connected to station T8400P3131352EDB on host 192.168.10.127 and port 13740
eufy  | 2022-05-24 09:39:58.900  INFO  Connected to station T8400P3131470E78 on host 192.168.10.202 and port 13740
eufy  | 2022-05-24 09:39:59.651  INFO  Push notification connection successfully established
```

Not sure what happened, I don't know that I did anything other than perhaps restarting the container. 

Anyway, I now have a _persistent.json_ file in the /data folder, but still no feed. 

I have tried to follow the instructions in the camera app, but it mentions entering an rtsp:// link somewhere in the RTSP server, but I don't see anyplace to do that, and in any case, I thought the server already picked up the cameras?

**Comment by bropat** [comment]
@Waldorf3 

The cause of the first error was a DNS problem (dns lookup from extend.eufylife.com failed).

With the second message, I don't really understand what you mean by:

> Anyway, I now have a persistent.json file in the /data folder, but still no feed.

> I have tried to follow the instructions in the camera app, but it mentions entering an rtsp:// link somewhere in the RTSP server, but I don't see anyplace to do that, and in any case, I thought the server already picked up the cameras?

Can you explain it to me in more detail so that I can follow you? Otherwise, I'm afraid I can't be of any help to you.

**Comment by Waldorf3** [comment]
Ok, this is my docker-compose.yml:
```
version: '2'
services:
  eufy:
    container_name: eufy
    image: bropat/eufy-security-ws
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - /media/private/eufy:/data
    environment:
      - USERNAME=(my email)
      - PASSWORD=(my password)
      - COUNTRY=US
      - LANGUAGE=en
      - ACCEPT_INVITATIONS=true
```

(replacing the email and password with the actual values). 

So under /data, that I mount at /media/private/eufy I have one file called persistent.json, nothing else. 

I then go to the app and select one of the cameras, then click the cog wheel (config button), then under General -> Storage - here I have 3 options: Local storage, Cloud Storage and NAS (RTSP). I select the last, NAS (RTSP). Here I select RTSP Stream (on), RTSP Security, it's preset with a username and password, Then I select between Events and Continuous recording, Events. There is a RTSP stream link, but I don't know what I need to use that for, there doesn't seem to be any place to enter it in the eufy-security-ws docker app.  Finally there are some parameters for the camera listed, again I don't know what I need to use them for as there doesn't seem to be anything to fill into the docker app. 

Hope this helps.
