### ISSUE TITLE
[Bug]: Video Doorbell E340 (T8214; Battery Powered) P2P not working

### ISSUE THREAD

**Issue by cyborcc** [bropat/eufy-security-ws#374]
### Version

1.9.1

### Node version

?

### Operating System type

Docker

### Operating system version

Hassio

### Describe the bug

https://github.com/fuatakgun/eufy_security/issues/1211

When using the T8214 camera, the P2P stream does not work. It shows preparing, but never streaming.
And the status is stuck at preparing for the camera.

### To reproduce

The moment I initiated the `start p2p stream` command in HA, the connection was closed becaus of saving battery, then disconnected and the live stream stopped on the add-on side.

### Screenshots & Logfiles

```
2024-11-13 20:35:03.620 INFO eufy-security-ws:eufy-security-client
[p2p] [Timeout._onTimeout] Initiated closing of connection to station xxxxx for saving battery.
2024-11-13 20:35:03.621 INFO eufy-security-ws:eufy-security-client
[http] [Station.onDisconnect] Disconnected from station xxxxx
2024-11-13 20:35:44.492 INFO eufy-security-ws:eufy-security-client
[http] [Station.onConnect] Connected to station xxxx on host xxx and port 10274
2024-11-13 20:35:49.868 INFO eufy-security-ws:eufy-security-client
[p2p] [Timeout._onTimeout] Stopping the station stream for the device xxxx, because we haven't received any data for 5 seconds ```


### Additional context

Home Assistant Installation Type (OS - Supvervised - Core): Home Assistant OS & Docker
Home Assistant Core Version: core-2024.10.3
Eufy Security Add-on Version: 1.9.1
Eufy Security Integration Version: 8.0.4

Hardware Information;
Camera Model: Eufy T8214
Live Streaming Protocol (RTSP/P2P): The camera only supports P2P

**Comment by s-hardt** [comment]
+1

**Comment by GurbirSD** [comment]
+1 for T8210C

**Comment by RGarrett93** [comment]
I wrote this automation to restart the addon when the doorbell gets stuck on preparing. It's a workaround that is working for me.

```
alias: Restart Eufy WS Add-on during lock up
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.front_door_stream_status
    for:
      hours: 0
      minutes: 1
      seconds: 0
    to: StreamStatus.PREPARING
conditions: []
actions:
  - action: hassio.addon_restart
    data:
      addon: 402f1039_eufy_security_ws
  - action: notify.mobile_app_your_mobile
    metadata: {}
    data:
      message: Eufy WS Add-on Restarted
      title: Eufy
mode: single
```
