### ISSUE TITLE
[Bug]: 1.9.2 workflow failing so no image pushed to DockerHub

### ISSUE THREAD

**Issue by matty87a** [bropat/eufy-security-ws#425]
### Version

1.9.2

### Node version

n/a

### Operating System type

Linux

### Operating system version

n/a

### Describe the bug

The 1.9.2 [release workflow failed](https://github.com/bropat/eufy-security-ws/actions/runs/14337655354) due to an issue with the npm ci command whilst running via the github action.

\as a local workaround it works fine if you clone 1.9.2 locallay and build via compose:

```
eufy-broker:
    #image: bropat/eufy-security-ws:1.9.1
    build:
      context: ./eufy-security-ws
      dockerfile: ./docker/Dockerfile
```

So the Dockerfile is fine, looks like the bulld context in the action is off.

This version (1.9.2) also seems to fix captcha failures (seen in 1.9.1) so hopefully this helps people out who are hitting that

### To reproduce

Run this: https://github.com/bropat/eufy-security-ws/actions/runs/14337655354

### Screenshots & Logfiles

```
0.799 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2025-04-08T16_57_35_510Z-debug-0.log
------
Dockerfile:4
--------------------
   2 |     WORKDIR /tmp
   3 |     COPY . .
   4 | >>> RUN npm ci && npm run build
   5 |     
   6 |     FROM node:20-alpine3.18 AS prod
--------------------
ERROR: failed to solve: process "/bin/sh -c npm ci && npm run build" did not complete 
```
